# Inleiding {-}

Dendrochronologie is de studie van groeiringen in houtige planten. Het is binnen de natuurwetenschappen een sterk uitgebouwd onderzoeksdomein met een eigen methodologie, dat ook daarbuiten vele praktische toepassingen kent. Binnen de erfgoedwereld bedienen het archeologisch, het historisch en het bouwhistorisch onderzoek zich van de resultaten van de dendrochronologie. En toch is niet iedereen binnen deze vakgebieden reeds ten volle op de hoogte van de mogelijkheden van het dendrochronologisch onderzoek. Nog te vaak verdwijnt oud hout, zonder dat het onderzocht is, bij archeologische opgravingen, bij de restauratie van bouwkundig erfgoed of bij de omgang met levend houtig erfgoed in onze landschappen.

Het onderwaarderen van oud hout als informatiebron in de context van erfgoedstudies heeft vooral te maken met een onderschatting van het potentieel aan informatie dat dendrochronologisch onderzoek kan bieden, niet enkel in een puur wetenschappelijke context maar ook in dossiers rond bescherming, behoud, beheer en studie van het boven- en ondergrondse erfgoed. Bovendien is er grote onzekerheid over wat een keuze van materiaal of staalname voor dendrochronologisch onderzoek precies inhoudt. Om de nodige kennis en ervaring te versterken, is wat toelichting op zijn plaats. 


>      
> **Dendrochronologie is de meest precieze natuurwetenschappelijke dateringstechniek.**
>    


In wat volgt, worden eerst de basisprincipes ([hoofdstuk 1](#basis)) van de dendrochronologie kort behandeld. Vanuit deze kennis worden een aantal onderzoeksvragen ([hoofdstuk 2](#onderzoeksvragen)) geformuleerd, relevant voor het onderzoek van houten constructies en voorwerpen met erfgoedwaarde, rekening houdend met een aantal randvoorwaarden ([hoofdstuk 3](#randvoorwaarden)). Na het eigenlijke onderzoek is uiteraard een correcte interpretatie van de onderzoeksresultaten ([hoofdstuk 4](#interpretatie) van belang. In deze handleiding wordt daarnaast ook voldoende aandacht besteed aan praktische richtlijnen voor: het nemen van de meest geschikte stalen van stukken hout met erfgoedwaarde ([hoofdstuk 5](#bemonsteren)), hun bewaring ([hoofdstuk 6](#bewaren)), de nodige documentatie ([hoofdstuk 7](#specialist)), de uiteindelijke analyse ([hoofdstuk 8](#analyse)) en de rapportage van het onderzoek ([hoofdstuk 9](#rapporteren)). Mocht een dendrochronologisch onderzoek uiteindelijk toch niet het gewenste resultaat opleveren, kan de wisselwerking met radiokoolstofdatering alsnog een uitweg bieden ([hoofdstuk 10](#C141)).