# Begrippen {-}


**Bast**: dit weefsel wordt door het cambium naar de buitenzijde van de boom aangemaakt. Het staat in voor transport van voedingsstoffen en andere assimilaten, die door fotosynthese in de bladeren worden aangemaakt, naar de overige delen van een boom. Aan de buitenzijde van de bast vormt zich een cambium dat kurkweefsel aanmaakt (= de schors).

**Boorkern**: cilinder van hout die uit een balk, stam of houten object wordt gehaald met behulp van een holle boor. Om bruikbaar te zijn voor dendrochronologisch onderzoek moet de boorrichting loodrecht op de jaarringen georiënteerd zijn.

**Cambium**: zie vasculair cambium

**Chronologie**: tijdreeks met metingen van een bepaalde karakteristiek (breedte, densiteit, aandeel vroeghout, …) van opeenvolgende jaarringen. De chronologie kan ook per kalenderjaar het gemiddelde (of andere afgeleide statistiek) weergeven van meerdere gesynchroniseerde (zie cross-dating) jaarringreeksen.

**Correlatiecoëfficiënt**: statistische maat die de samenhang/overeenkomst tussen twee variabelen uitdrukt. Een hoge correlatiecoëfficiënt geeft aan dat de waarden van de beide variabelen een zelfde (positieve correlatiecoëfficiënt) of een tegengesteld (negatieve correlatiecoëfficiënt) verband vertonen.

**Cross-dating**: bij dit basisprincipe van de dendrochronologie wordt er vanuit gegaan dat bomen die over een bepaalde tijdsperiode gelijkaardige groeiomstandigheden ondervinden (klimaat, bodem, hoogteligging, …), ook een gelijkaardig groeiringpatroon zullen ontwikkelen. Daardoor kunnen jaarringreeksen van een specifieke boomsoort uit een bepaalde regio onderling, tot op het kalenderjaar precies, gesynchroniseerd worden, op basis van de unieke afwisseling van brede en smalle ringen.

**Dendrochronologie** of **jaarringonderzoek**: is de wetenschappelijke discipline waarbij de datering van groeiringen in hout centraal staat. De opeenvolgende groeiringen worden hierbij beschouwd als een kalender, waarbij men als het ware terug kan gaan in de tijd door de groeiringen van een boom één voor één te registreren.

**Dendro-klimatologie**: de studie van het klimaat in het verleden met behulp van gedateerde jaarringreeksen.

**Dendro-provenancing**: bepaling van het oorspronggebied van hout aan de hand van het jaarringpatroon. 

**Floëem**: bastweefsel. Dit weefsel staat in voor het transport van voedingsstoffen en andere assimilaten, die door fotosynthese in de bladeren worden aangemaakt, naar andere delen van de boom. Nieuw floëemweefsel ontstaat door celdeling en -differentiatie vanuit het vasculair cambium.

**Houtanatomie**: de studie en gedetailleerde beschrijving van de anatomische opbouw van hout.

**Houtstraal**: weefsel in het hout dat straalsgewijs is georiënteerd. De houtstralen zorgen voor het horizontale (radiale) transport van water en voedingsstoffen en de opslag van reservestoffen.

**Houtvaten**: reeks van korte, boven elkaar gelegen cellen waarvan de onderlinge tussenschotten verdwenen zijn. Daardoor vormen ze samen een doorlopend, buisvormig netwerk. Op een dwarse doorsnede zijn deze vaten te herkennen als ronde of ovale poriën.

**Jaarring**: de houtaanwas, gezien op het transversaal vlak, van één groeiperiode. Wanneer de groeiring een jaarlijkse aanwas is, wordt hij jaarring genoemd, bestaande uit vroeghout (of lentehout) en laathout (of zomerhout).

**Kernhout**: dood houtweefsel waarin geen actief transport van water en voedingsstoffen meer kan plaatsvinden. Het bevindt zich in het centrale gedeelte van de stam en grenst aan het spinthout.

**Laathout**: deel van de groeiring dat later op het groeiseizoen wordt gevormd en zich dikwijls onderscheidt van het vroeghout door een dichtere opbouw.

**Merg**: het (parenchymatisch) weefsel in het centrum van de stam of wortel.

**Ringporig hout**: loofhout waarbij opvallend grotere vaten zijn gevormd aan het begin van het groeiseizoen (in het vroeghout) gevolgd door een zone, binnen dezelfde jaarring, met duidelijk kleinere vaten (het laathout).

**Schors**: het weefsel dat zich aan de buitenzijde van stam en wortels bevindt. Het bestaat grotendeels uit dode cellen (kurkweefsel) dat wordt aangemaakt vanuit een cambium, op de overgang tussen schors en bast.

**Spinthout**: fysiologisch actief deel van het hout. Het spinthout is het levende houtweefsel dat de sapstroom verzorgt in de stam en dient als opslagplaats voor voedingsstoffen. Het heeft exact dezelfde structuur als het kernhout, maar bij het spinthout zijn de transportkanalen (vaten) nog grotendeels vrij. Het bevindt zich tussen het kernhout en de bast van de boom Het spinthout is bij eik, net zoals bij veel andere houtsoorten, gekenmerkt door een lichtere kleur dan het kernhout.

**Subfossiel**: eeuwenoude, niet volledig gefossiliseerde resten van dieren of planten. In tegenstelling tot fossiel materiaal, waar de oorspronkelijke organische weefsels volledig vervangen zijn door een minerale matrix, is bij subfossiele resten het oorspronkelijke organische materiaal nog (gedeeltelijk) bewaard.

**Synchroniseren**: zie cross-dating.

**Terminus post quem**: vroegst mogelijke tijdstip (ondergrens) waarop een gebeurtenis kan hebben plaatsgevonden.

**Terminus ante quem**: laatst mogelijke tijdstip (bovengrens) waarop een gebeurtenis kan hebben plaatsgevonden.

**Vasculair cambium**: weefsellaag aan de buitenzijde van de stam of takken van struiken en bomen, waar nieuwe cellen worden aangemaakt. Dit (deel)weefstel zorgt voor de aanmaak van nieuw hout (xyleem) en bast (floëem).

**Verspreidporig hout**: loofhout met een uniforme verdeling van de vaten over de groeiring.

**Vroeghout**: het deel van de groeiring dat bij de aanvang van het groeiseizoen wordt gevormd. Het is bij veel houtsoorten te herkennen aan een meer poreuze en lichtere opbouw dan het later op het groeiseizoen gevormde laathout.

**Wankant**: de overgang tussen hout en bast. Dit komt overeen met de zone waar het cambium te vinden is. Naar de binnenzijde toe grenst het aan de meest recent gevormde groeiring.

**Wiggle-matching**: combinatie van meerdere radiokoolstofdateringen met een onderling gekende tussenafstand of schikking in de tijd om zo de precisie van de gekalibreerde radiokoolstofdateringen te verhogen. Indien wiggle-matching wordt toegepast op één of meerdere stukken hout, kan de chronologische afstand tussen twee bemonsteringspunten exact bepaald worden door het aantal tussenliggende jaarringen te tellen.

**Xyleem**: houtweefsel. Dit weefsel staat in voor het transport van water, en daarin opgeloste stoffen, van de wortels naar de bladeren toe. Nieuw xyleemweefsel ontstaat door celdeling en -differentiatie vanuit het vasculair cambium.
