project:
  type: book
  output-dir: docs

execute:
  echo: false

lang: nl

book:
  title: "Dendrochronologie en erfgoedonderzoek"
  subtitle: "-- een handleiding"
  author: 
    - name: Kristof Haneca
      orcid: 0000-0002-7719-8305
      affiliation: "agentschap Onroerend Erfgoed"
  
  publisher: "agentschap Onroerend Erfgoed"
  date: today
  cover-image: figuren/cover_handleiding.jpg

  bread-crumbs: false
  reader-mode: true
  
  repo-url: https://github.com/ErfgoedPublicaties/HAOE-16-Dendrochronologie/
  repo-branch: master
  repo-actions: [edit, issue]
  site-url: https://publicaties.onroerenderfgoed.be/HAOE-16-Dendrochronologie/
  
  chapters:
    - index.qmd
    - 00_dendro_wijzigingen.qmd
    - part: "Handleiding"
      chapters:
      - 01_dendro_intro.qmd
      - 02_dendro_principes.qmd
      - 03_dendro_onderzoeksvragen.qmd
      - 04_dendro_randvoorwaarden.qmd
      - 05_dendro_bemonsteren.qmd
      - 06_dendro_bewaren.qmd
      - 07_dendro_overdracht.qmd
      - 08_dendro_analyseren.qmd
      - 09_dendro_rapporteren.qmd
      - 10_dendro_interpretatie.qmd
      - 11_dendro_radiokoolstof.qmd
    - part: "Begrippen"
      chapters: 
      - 999_dendro_begrippen.qmd
    - part: "Bronnen"
      chapters: 
      - 999_dendro_bibliografie.qmd
    
title-block-banner: "#0e4d1c"
title-block-banner-color: white

bibliography: dendro_biblio.bib
csl: elsevier-harvard_nl.csl

engine: knitr

crossref:
  fig-title: Figuur
  fig-prefix: fig.
  tbl-title: Tabel
  tbl-prefix: tabel
  
language:
  toc-title-document: "Op deze pagina"
  search-no-results-text: "Geen resultaat"
  repo-action-links-edit: "Bewerk deze pagina"
  title-block-author-plural: "auteurs"
  title-block-published: "laatste update"
  title-block-affiliation-plural: "affiliatie"

filters:
   - lightbox
lightbox: auto

format:
  html:
    theme:
      light:
        - cosmo
        - mycss.css
      dark:
        - slate
        - mycss.css
    linkcolor: "#3E7049"
    toc-depth: 4
    link-external-newwindow: true
